export const marcas = [
  { id: 1, nombre: 'Ford', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/03/Logo-Ford-negro.png' },
  { id: 2, nombre: 'Changan', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-CHANGAN-negro.png' },
  { id: 3, nombre: 'Mazda', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-MAZDA-negro.png' },
  { id: 4, nombre: 'Jetour', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/Jetour-Logo-scaled.png' },
  { id: 5, nombre: 'Suzuki', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-SUZUKI-negro.png' },
  { id: 6, nombre: 'GWM', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-GWM-negro.png' },
  { id: 7, nombre: 'Haval', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-HAVAL-negro.png' },
  { id: 8, nombre: 'Renault', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-RENAULT-negro.png' },
  { id: 9, nombre: 'JAC', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/01/LOGO-JAC-negro.png' },
  { id: 10, nombre: 'KYC', logo: 'https://revoshop.com.pe/wp-content/uploads/2026/03/logo-KYC.png' },
];

export const categorias = [
  { id: 1, nombre: 'SUV', icono: '🚙' },
  { id: 2, nombre: 'Sedán', icono: '🚗' },
  { id: 3, nombre: 'Hatchback', icono: '🚘' },
  { id: 4, nombre: 'Pick Up', icono: '🚛' },
  { id: 5, nombre: 'Híbridos', icono: '⚡' },
  { id: 6, nombre: 'Van', icono: '🚐' },
];

export const autos = [
  {
    id: 1,
    nombre: 'AVP Furgón',
    marca: 'SUZUKI',
    tipo: 'Van',
    precioUSD: 17090,
    precioPEN: 59815,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2026/03/avp-furgon-suzuki-portada-660x440.png',
    km: 'Miles',
    transmision: 'Mecánico (MT)',
    destacado: true,
    nuevo: false,
  },
  {
    id: 2,
    nombre: 'Mazda 2 Sedán',
    marca: 'MAZDA',
    tipo: 'Sedán',
    precioUSD: 19790,
    precioPEN: 69265,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2026/03/PORTADA-14-660x440.png',
    km: 'Miles',
    transmision: 'Automática',
    destacado: true,
    nuevo: false,
  },
  {
    id: 3,
    nombre: 'Mazda 3 Sport',
    marca: 'MAZDA',
    tipo: 'Hatchback',
    precioUSD: 26190,
    precioPEN: 91665,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2026/03/mazda-3-sport-660x440.png',
    km: 'Miles',
    transmision: 'Automático',
    destacado: false,
    nuevo: false,
  },
  {
    id: 4,
    nombre: 'CS55 Plus IDD',
    marca: 'CHANGAN',
    tipo: 'SUV',
    precioUSD: 25990,
    precioPEN: 90965,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2026/03/cs55-plus-idd-portada-660x440.png',
    km: '0 Miles',
    transmision: 'DHT',
    destacado: false,
    nuevo: true,
  },
  {
    id: 5,
    nombre: 'New CS55 Plus',
    marca: 'CHANGAN',
    tipo: 'Sedan',
    precioUSD: 18490,
    precioPEN: 66564,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/new-cs55-plus-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: '7DCT (Sec.)',
    destacado: false,
    nuevo: true,
  },
  {
    id: 6,
    nombre: 'UNI-T',
    marca: 'CHANGAN',
    tipo: 'Sedan',
    precioUSD: 21990,
    precioPEN: 79164,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/unit-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: 'Automático',
    destacado: false,
    nuevo: false,
  },
  {
    id: 7,
    nombre: 'UNI-K',
    marca: 'CHANGAN',
    tipo: 'SUV',
    precioUSD: 33490,
    precioPEN: 120564,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/unik-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: '8 AT AISIN',
    destacado: false,
    nuevo: false,
  },
  {
    id: 8,
    nombre: 'X7 Plus',
    marca: 'CHANGAN',
    tipo: 'SUV',
    precioUSD: 17190,
    precioPEN: 61884,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/x7plus-changan-660x440.png',
    km: 'Miles',
    transmision: 'Aut. 7 DCT',
    destacado: false,
    nuevo: false,
  },
  {
    id: 9,
    nombre: 'New Van',
    marca: 'CHANGAN',
    tipo: 'Van',
    precioUSD: 10190,
    precioPEN: 36684,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/new-van-changan-plata-660x440.png',
    km: '0 Miles',
    transmision: 'Gasolina 5 velocidades',
    destacado: false,
    nuevo: true,
  },
  {
    id: 10,
    nombre: 'New CS35 Plus',
    marca: 'CHANGAN',
    tipo: 'Sedan',
    precioUSD: 16090,
    precioPEN: 57924,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/cs35-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: 'Aut. 7 DCT',
    destacado: false,
    nuevo: true,
  },
  {
    id: 11,
    nombre: 'New CS15',
    marca: 'CHANGAN',
    tipo: 'Sedan',
    precioUSD: 12490,
    precioPEN: 44964,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/new-cs15-portada-changan-660x440.png',
    km: '0 Miles',
    transmision: 'Gasolina 5 velocidades',
    destacado: false,
    nuevo: true,
  },
  {
    id: 12,
    nombre: 'Honor S',
    marca: 'CHANGAN',
    tipo: 'Sedan',
    precioUSD: 12790,
    precioPEN: 46044,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/honor-s-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: 'Gasolina 5 velocidades',
    destacado: false,
    nuevo: false,
  },
  {
    id: 13,
    nombre: 'Grand Van Turismo',
    marca: 'CHANGAN',
    tipo: 'Van',
    precioUSD: 15490,
    precioPEN: 55764,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/gran-van-turismo-portada-660x440.png',
    km: '0 Miles',
    transmision: '5MT',
    destacado: false,
    nuevo: false,
  },
  {
    id: 14,
    nombre: 'Grand Supervan Plus',
    marca: 'CHANGAN',
    tipo: 'Van',
    precioUSD: 12990,
    precioPEN: 46764,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/grand-supervan-plus-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: '5MT',
    destacado: false,
    nuevo: false,
  },
  {
    id: 15,
    nombre: 'F70',
    marca: 'CHANGAN',
    tipo: 'Pick Up',
    precioUSD: 19090,
    precioPEN: 68724,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/f70-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: '6 MT + R',
    destacado: false,
    nuevo: false,
  },
  {
    id: 16,
    nombre: 'New Alsvin',
    marca: 'CHANGAN',
    tipo: 'Sedan',
    precioUSD: 10990,
    precioPEN: 39564,
    imagen: 'https://revoshop.com.pe/wp-content/uploads/2025/09/alsvin-changan-portada-660x440.png',
    km: '0 Miles',
    transmision: '5 velocidades',
    destacado: false,
    nuevo: true,
  },
];